sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install: "make"
script: make ci
jobs:
  include:
    - stage: test
      script: make ci
    - stage: docs
      python: 3.6
      script: make docs
